spring:
  application:
    name: task-management-service
  jackson:
    date-format: dd-MM-yyyy
  datasource:
    url: jdbc:postgresql://localhost:5434/task_management
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    host: localhost:9092
    topics:
      task-created:
        topicName: create_assign_task
        partitionCount: 1
        replicationFactor: 1
      task-completed:
        topicName: task_completed
        partitionCount: 1
        replicationFactor: 1



server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

